---
branches:
  only:
    - master
language: ruby
bundler_args: --without development
script: bundle exec rake test SPEC_OPTS='--format documentation'
after_success:
  - git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-releng
  - .forge-releng/publish
sudo: false
cache: bundler
env:
  global:
  - PUBLISHER_LOGIN=bodgit
  - secure: |-
      DDlkaixEXGc0vQ631mfAMkPYhpyb5WL8bXngCwXoBhEfKCnbFzfhnyjjl2UB/yhJB
      KYRVeEwgpHYRUsidy91FWSpcpw/02w1HXmoQDysPgEYYGsTufuTvBwWffDXIdpOVe
      wKCApdlWFSxyQNaevfo/JFK9v21Zth7jN8FPcsJ1s=
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
notifications:
  email: false
